//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopulationCensu
    {
        public int ApplicationID { get; set; }
        public int Memberid { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string suffix { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
    }
}
